In [1]:
import pandas as pd
import numpy as np
import os
import glob
import torch
from transformers import AutoTokenizer, AutoModel
from sklearn.model_selection import train_test_split
import xgboost as xgb
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder

In [2]:
# 2021

df = pd.read_excel("財務數據excel/2021data.xls", header=7)
df['Exchange:Ticker'] = df['Exchange:Ticker'].str.split(':').str[-1]
df = df.drop(columns=["Company Name", 
                        "SIC Codes", 
                        "SIC Codes (Primary Code Only)",
                        "SIC Codes (Primary)", 
                        "Company Type",
                        "Total Trading Assets, Dom. - Capital IQ [CY 2021] ($USDmm, Historical rate)",
                        "Retained Earnings - Capital IQ [CY 2021] ($USDmm, Historical rate)"])

rating_list = ['A', 
                'A+',
                'A-', 
                'AA',
                'AA+',
                'AA-',
                'AAA',
                'B',
                'B+',
                'B-',
                'BB',
                'BB+',
                'BB-',
                'BBB',
                'BBB+',
                'BBB-',
                'CCC',
                'CCC+',
                'CCC-',
                'D']

rating_map = {
    'AAA': 1, 'AA+': 1, 'AA': 1, 'AA-': 1, 'A+': 1, 'A': 1, 'A-': 1,
    'BBB+': 2, 'BBB': 2, 'BBB-': 2,
    'BB+': 3, 'BB': 3, 'BB-': 3,
    'B+': 4, 'B': 4, 'B-': 4, 'CCC+': 4, 'CCC': 4, 'CCC-': 4, 'D': 4,
    'NR': np.nan
}

# 创建一个新的 DataFrame，并将评级映射到数值
df['S&P Entity Credit Rating - Issuer Credit Rating - Local Currency LT [Latest] (Rating)'] = df['S&P Entity Credit Rating - Issuer Credit Rating - Local Currency LT [Latest] (Rating)'].map(lambda x: rating_map.get(x, x))

# 以下等資料補齊後就可以刪掉
for col in df.columns:
    df[col] = df[col].replace('-', np.nan)
df["Payout Ratio - Capital IQ [CY 2021] (%)"] = df["Payout Ratio - Capital IQ [CY 2021] (%)"].replace('NM', np.nan)
for col in df.columns:
    if col in ["Exchange:Ticker","S&P Entity Credit Rating - Issuer Credit Rating - Local Currency LT [Latest] (Rating)"]:
        df[col] = df[col].fillna(df[col].mode().iloc[0])  
    else:
        df[col] = df[col].fillna(df[col].mean())  

for ticker in df['Exchange:Ticker']:
    txt_files = glob.glob(os.path.join('10-K文字檔/2021data/', f"{ticker}_*.txt"))
    if txt_files:
        # 讀取第一個匹配的文件內容
        with open(txt_files[0], 'r') as f:
            content = f.read()
        # 將內容添加到df的新欄位中
        df.loc[df['Exchange:Ticker'] == ticker, 'text'] = content
    else:
        # 如果沒有找到匹配的文件,可以在新欄位中填寫一些默認值
        df.loc[df['Exchange:Ticker'] == ticker, 'text'] = np.nan

# 股票代碼沒對到的資料刪掉        
df = df.dropna() 

df

Exchange:Ticker  \
1               FLWS   
3                TXG   
5               EFSH   
7               SRCE   
9               XXII   
...              ...   
4287              ZI   
4288              ZS   
4289            ZUMZ   
4290             ZUO   
4294            ZYXI   

      S&P Entity Credit Rating - Issuer Credit Rating - Local Currency LT [Latest] (Rating)  \
1                                                   2.0                                       
3                                                   2.0                                       
5                                                   2.0                                       
7                                                   2.0                                       
9                                                   2.0                                       
...                                                 ...                                       
4287                                                3.0                                       
4288                                                2.0                                       
4289                                                2.0                                       
4290                                                2.0                                       
4294                                                2.0                                       

      Total Assets - Capital IQ [CY 2021] ($USDmm, Historical rate)  \
1                                                1321.3               
3                                                1018.8               
5                                                  47.0               
7                                                8096.3               
9                                                  76.0               
...                                                 ...               
4287                                             6852.9               
4288                                             2422.0               
4289                                              862.0               
4290                                              441.3               
4294                                              133.3               

      Total Capital - Capital IQ [CY 2021] ($USDmm, Historical rate)  \
1                                             877.80000                
3                                             899.50000                
5                                              33.90000                
7                                            7111.43281                
9                                              68.40000                
...                                                 ...                
4287                                         3306.00000                
4288                                         1529.00000                
4289                                          736.20000                
4290                                          229.40000                
4294                                          109.00000                

      Sales/Sq. Ft., All (Net) - Capital IQ [CY 2021] ($USD, Historical rate)  \
1                                                327.54                         
3                                                327.54                         
5                                                327.54                         
7                                                327.54                         
9                                                327.54                         
...                                                 ...                         
4287                                             327.54                         
4288                                             327.54                         
4289                                             327.54                         
4290                                           

In [ ]:
# 2022

df = pd.read_excel("財務數據excel/2022data.xls", header=7)
df['Exchange:Ticker'] = df['Exchange:Ticker'].str.split(':').str[-1]
df = df.drop(columns=["Company Name", 
                        "SIC Codes", 
                        "SIC Codes (Primary Code Only)",
                        "SIC Codes (Primary)", 
                        "Company Type",
                        "Total Trading Assets, Dom. - Capital IQ [FY 2022] ($USDmm, Historical rate)",
                        "Retained Earnings - Capital IQ [FY 2022] ($USDmm, Historical rate)"])

rating_list = ['A', 
                'A+',
                'A-', 
                'AA',
                'AA+',
                'AA-',
                'AAA',
                'B',
                'B+',
                'B-',
                'BB',
                'BB+',
                'BB-',
                'BBB',
                'BBB+',
                'BBB-',
                'CCC',
                'CCC+',
                'CCC-',
                'D']

rating_map = {
    'AAA': 1, 'AA+': 1, 'AA': 1, 'AA-': 1, 'A+': 1, 'A': 1, 'A-': 1,
    'BBB+': 2, 'BBB': 2, 'BBB-': 2,
    'BB+': 3, 'BB': 3, 'BB-': 3,
    'B+': 4, 'B': 4, 'B-': 4, 'CCC+': 4, 'CCC': 4, 'CCC-': 4, 'D': 4,
    'NR': np.nan
}

# 创建一个新的 DataFrame，并将评级映射到数值
df['S&P Entity Credit Rating - Issuer Credit Rating - Local Currency LT [Latest] (Rating)'] = df['S&P Entity Credit Rating - Issuer Credit Rating - Local Currency LT [Latest] (Rating)'].map(lambda x: rating_map.get(x, x))

# 以下等資料補齊後就可以刪掉
for col in df.columns:
    df[col] = df[col].replace('-', np.nan)
df["Payout Ratio - Capital IQ [FY 2022] (%)"] = df["Payout Ratio - Capital IQ [FY 2022] (%)"].replace('NM', np.nan)

for col in df.columns:
    if col in ["Exchange:Ticker","S&P Entity Credit Rating - Issuer Credit Rating - Local Currency LT [Latest] (Rating)"]:
        df[col] = df[col].fillna(df[col].mode().iloc[0])  
    else:
        df[col] = df[col].fillna(df[col].mean())  

for ticker in df['Exchange:Ticker']:
    txt_files = glob.glob(os.path.join('10-K文字檔/2021data/', f"{ticker}_*.txt"))
    if txt_files:
        # 讀取第一個匹配的文件內容
        with open(txt_files[0], 'r') as f:
            content = f.read()
        # 將內容添加到df的新欄位中
        df.loc[df['Exchange:Ticker'] == ticker, 'text'] = content
    else:
        # 如果沒有找到匹配的文件,可以在新欄位中填寫一些默認值
        df.loc[df['Exchange:Ticker'] == ticker, 'text'] = np.nan

# 股票代碼沒對到的資料刪掉        
df = df.dropna() 

df

In [3]:
df = df.sample(n=300, random_state=42)

In [4]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")
model = AutoModel.from_pretrained("distilbert-base-uncased").to(device)

df_train, df_val = train_test_split(df, test_size=0.2, random_state=42)

general_features_train = df_train.iloc[:,2:-1]
general_features_val = df_val.iloc[:,2:-1]

In [5]:
tokenized_train = tokenizer(df_train["text"].values.tolist(), padding = True, truncation = True, return_tensors="pt")
tokenized_val = tokenizer(df_val["text"].values.tolist() , padding = True, truncation = True,  return_tensors="pt")

with torch.no_grad():
    hidden_train = model(**tokenized_train)
    hidden_val = model(**tokenized_val)

#get only the [CLS] hidden states
cls_train = hidden_train.last_hidden_state[:,0,:]
cls_val = hidden_val.last_hidden_state[:,0,:]

In [6]:
le = LabelEncoder()

x_train = torch.cat((cls_train, torch.from_numpy(general_features_train.values)), 1)
y_train = df_train["S&P Entity Credit Rating - Issuer Credit Rating - Local Currency LT [Latest] (Rating)"]
y_train = le.fit_transform(y_train)

x_val = torch.cat((cls_val, torch.from_numpy(general_features_val.values)), 1)
y_val = df_val["S&P Entity Credit Rating - Issuer Credit Rating - Local Currency LT [Latest] (Rating)"]
y_val = le.fit_transform(y_val)

print(x_train.shape, y_train.shape, x_val.shape, y_val.shape)

torch.Size([240, 785]) (240,) torch.Size([60, 785]) (60,)


In [7]:
# 創建 XGBoost 模型
model = xgb.XGBClassifier(objective='multi:softprob',
                            n_estimators=1000,
                            max_depth=7,
                            learning_rate=0.1,
                            random_state=42)

# 訓練模型
model.fit(x_train, y_train)

# 在驗證集上進行預測
y_val_pred = model.predict(x_val)

# 計算評估指標
acc = accuracy_score(y_val, y_val_pred)
f1 = f1_score(y_val, y_val_pred, average='weighted')
precision = precision_score(y_val, y_val_pred, average='weighted')
recall = recall_score(y_val, y_val_pred, average='weighted')
cm = confusion_matrix(y_val, y_val_pred)

print(f"Accuracy: {acc:.2f}")
print(f"F1-score: {f1:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print("Confusion Matrix:")
print(cm)

Accuracy: 0.67
F1-score: 0.59
Precision: 0.52
Recall: 0.67
Confusion Matrix:
[[ 0  3  0  0]
 [ 1 40  1  2]
 [ 0  8  0  0]
 [ 0  5  0  0]]


In [8]:
df_val

Exchange:Ticker  \
1336             ENG   
415             ATNI   
2823            OPEN   
3288             RTX   
1847             HXL   
4070            VRCA   
3958            UCTT   
3829             THR   
449              RNA   
1543            FFIC   
2692            NICK   
2411             MAS   
3718             TPL   
2115            FROG   
4148             WNC   
1085            CGEM   
4030             MTN   
1756             GPI   
3706             TEX   
2136            KSPN   
668               BV   
3466            SMBK   
760             CARG   
1493            BUSE   
3518             SSB   
2211             LHX   
1273            ECVT   
2423            MATV   
3758              EL   
2486            MCHP   
2516              MG   
3729            ANDE   
2288            LWLG   
967             CBSH   
1506             FHB   
4188            WNEB   
2310            LIVE   
2061            IONS   
1537             FLO   
3588             SRI   
1831              HP   
3876            TRNS   
1825            HSII   
831             CERS   
1631             GCI   
4172             WEC   
1284            EGAN   
696             BURL   
3738             SAM   
875             CHDN   
692             BMBL   
2409            MMLP   
3985            UTHR   
4034             VMI   
3205              RS   
1923            ICCH   
722             CAMP   
3791            MIDD   
2145             KMT   
3934            TWLO   

      S&P Entity Credit Rating - Issuer Credit Rating - Local Currency LT [Latest] (Rating)  \
1336                                                2.0                                       
415                                                 2.0                                       
2823                                                2.0                                       
3288                                                2.0                                       
1847                                                3.0                                       
4070                                                2.0                                       
3958                                                4.0                                       
3829                                                2.0                                       
449                                                 2.0                                       
1543                                                2.0                                       
2692                                                2.0                                       
2411                                                2.0                                       
3718                                                2.0                                       
2115                                                2.0                                       
4148                                                3.0                                       
1085                                                2.0                                       
4030                                                3.0                                       
1756                                                3.0                                       
3706                                                3.0                                       
2136                                                2.0                                       
668                                                 2.0                                       
3466                                                2.0                                       
760                                                 2.0                                       
1493                                                2.0                                       
3518                                                2.0                                       
2211                                                2.0               

In [9]:
y_val_pred

array([1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1], dtype=int64)